CREATE TABLE `loan_services` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`contact_name` text DEFAULT '' NOT NULL,
	`service_type` text DEFAULT '' NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`specialties` text DEFAULT '' NOT NULL,
	`address` text DEFAULT '' NOT NULL,
	`city` text DEFAULT '' NOT NULL,
	`state` text DEFAULT '' NOT NULL,
	`zip` text DEFAULT '' NOT NULL,
	`service_area` text DEFAULT '' NOT NULL,
	`phone` text DEFAULT '' NOT NULL,
	`email` text DEFAULT '' NOT NULL,
	`website` text DEFAULT '' NOT NULL,
	`logo_url` text DEFAULT '' NOT NULL,
	`rabbinical_oversight` text DEFAULT '' NOT NULL,
	`kosher_details` text DEFAULT '' NOT NULL,
	`verification_status` text DEFAULT 'Verified' NOT NULL,
	`last_verified` text DEFAULT '' NOT NULL,
	`public_notes` text DEFAULT '' NOT NULL,
	`internal_notes` text DEFAULT '' NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`featured` integer DEFAULT false NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
