CREATE TABLE `investment_opportunities` (
	`id` text PRIMARY KEY NOT NULL,
	`opportunity_name` text NOT NULL,
	`sponsor_name` text DEFAULT '' NOT NULL,
	`investment_type` text DEFAULT '' NOT NULL,
	`description` text DEFAULT '' NOT NULL,
	`minimum_investment` text DEFAULT '' NOT NULL,
	`return_information` text DEFAULT '' NOT NULL,
	`investment_term` text DEFAULT '' NOT NULL,
	`location` text DEFAULT '' NOT NULL,
	`availability_status` text DEFAULT 'Open' NOT NULL,
	`kosher_status` text DEFAULT 'Reviewed' NOT NULL,
	`rabbinical_oversight` text DEFAULT '' NOT NULL,
	`kosher_details` text DEFAULT '' NOT NULL,
	`last_reviewed` text DEFAULT '' NOT NULL,
	`risk_disclosure` text DEFAULT '' NOT NULL,
	`contact_name` text DEFAULT '' NOT NULL,
	`phone` text DEFAULT '' NOT NULL,
	`email` text DEFAULT '' NOT NULL,
	`opportunity_url` text DEFAULT '' NOT NULL,
	`logo_url` text DEFAULT '' NOT NULL,
	`public_notes` text DEFAULT '' NOT NULL,
	`internal_notes` text DEFAULT '' NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`featured` integer DEFAULT false NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
